### ISSUE TITLE
Рефакторинг

### ISSUE THREAD

**Issue by ignavan39** [LeenDrew/mark-yourself#1]
- [ ] Типов в хэлперах точно не должно быть сделай отдельную папку в корне и назови ее type и складывай туда типы в файлы на примере: 
types/*.type.ts
https://github.com/LeenDrew/mark-yourself/blob/64179a6972519ae4fef99bafe025eb6c0390096a/src/helpers/univ.api.ts#L3

- [ ] 1. это должно вообще быть в scr, 2. доставай это из переменных окружения 3. реализуй синглтон
https://github.com/LeenDrew/mark-yourself/blob/64179a6972519ae4fef99bafe025eb6c0390096a/config/index.example.ts#L1

- [ ] это тоже в types, здесь этому не место https://github.com/LeenDrew/mark-yourself/blob/64179a6972519ae4fef99bafe025eb6c0390096a/src/bot/index.ts#L13

- [x] так делать не надо, нарушается DI - складывай это все в класс https://github.com/LeenDrew/mark-yourself/blob/64179a6972519ae4fef99bafe025eb6c0390096a/src/controllers/group-controller.ts#L3

- [x] не надо называть файлы camelCase - так и пиши sub-group.controller.ts
- [x] и тот же пойнт что и выше, скалдывай в класс потому что не понятно что getMany - чего
https://github.com/LeenDrew/mark-yourself/blob/64179a6972519ae4fef99bafe025eb6c0390096a/src/controllers/subGroup-controller.ts#L3

- [x] у тебя достается вся сущность чтобы проверить что она существует, проверь есть ли в монге аналог COUNT или вообще мб есть такой метод exist, долгий запрос
- [x] + тот же поинт - сложи в класс 
https://github.com/LeenDrew/mark-yourself/blob/64179a6972519ae4fef99bafe025eb6c0390096a/src/controllers/user-controller.ts#L11

- [x] форматирование https://github.com/LeenDrew/mark-yourself/blob/64179a6972519ae4fef99bafe025eb6c0390096a/src/controllers/user-controller.ts#L31
https://github.com/LeenDrew/mark-yourself/blob/64179a6972519ae4fef99bafe025eb6c0390096a/src/controllers/user-controller.ts#L38

- [x] коменнтарии к коду - означают что в коде не понятно чо происходит (C) Robert Martin Clean Code 
такие штуки удаляй перед коммитов либо осталвяй ПР в состоянии WIP
- [x] перенеси это в common/middlewares там реализуй а здесь юзай
https://github.com/LeenDrew/mark-yourself/blob/64179a6972519ae4fef99bafe025eb6c0390096a/src/bot/index.ts#L31

- [ ] тот же поинт реализуй класс, потому что это все таки ближе к ООП 
https://github.com/LeenDrew/mark-yourself/blob/64179a6972519ae4fef99bafe025eb6c0390096a/src/bot/index.ts#L22

- [x] 1. ни в коем случае не называй интерфейсы с IUser, IGroup  и тд, это ужасный подход который так же критикуется в книге Чистый код, хочешь назвои интерфейс Group а класс GroupImpl
- [x] название файла с маленькой буквы 
- [x] убери комментарии и так понятно что происходит 
- [ ] export default - зло
- [x] остальные файлы потому же принципу пофиксь
https://github.com/LeenDrew/mark-yourself/blob/64179a6972519ae4fef99bafe025eb6c0390096a/src/models/Group.ts#L3

- [ ] это к подгруппе больше относиться чем к утилитам засунь в класс
https://github.com/LeenDrew/mark-yourself/blob/64179a6972519ae4fef99bafe025eb6c0390096a/src/utils/index.ts#L11

- [ ] не возвращай пайпы, сделай toPromise или Last, в общем исправь тип возвращаемый 
https://github.com/LeenDrew/mark-yourself/blob/64179a6972519ae4fef99bafe025eb6c0390096a/src/helpers/univ.api.ts#L45

важный поинт - делай ПРы, чтобы было проще ревьювить и отслеживать изменения

**Comment by kitt3911** [comment]
- [ ] вообще по конвенции метод update - возвращает результат апдейта) 
 https://github.com/LeenDrew/mark-yourself/commit/64179a6972519ae4fef99bafe025eb6c0390096a#diff-9688f93a21faded3ba6ad74f7287f84a6921aeeacfe9d44f9f169cb1961041c8R31

**Comment by kitt3911** [comment]
- [ ] Добавь скрипт для форматирования, не помешает 
https://github.com/LeenDrew/mark-yourself/blob/64179a6972519ae4fef99bafe025eb6c0390096a/package.json#L9
